name: Label PR by Branch

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        run: |
          source_branch=$(jq -r '.pull_request.head.ref' $GITHUB_EVENT_PATH)
          target_branch=$(jq -r '.pull_request.base.ref' $GITHUB_EVENT_PATH)
        id: get_branch_names

      - name: Label PR with source branch name
        uses: peter-evans/create-issue-from-file@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "source: ${{ steps.get_branch_names.outputs.source_branch }}"
          labels: "source branch"
          assignees: ${{ github.event.pull_request.user.login }}

      - name: Label PR with target branch name
        uses: peter-evans/create-issue-from-file@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "target: ${{ steps.get_branch_names.outputs.target_branch }}"
          labels: "target branch"
          assignees: ${{ github.event.pull_request.user.login }}
