name: PR Processing

on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Get source and target branch names
        run: |
          echo "Source branch name: ${{ github.event.pull_request.head.ref }}"
          echo "Target branch name: ${{ github.event.pull_request.base.ref }}"
        id: get_branches

      - name: Label pull request with source and target branch names
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const source = context.payload.pull_request.head.ref;
            const target = context.payload.pull_request.base.ref;
            const sourceLabelText = `Source: ${source}`;
            const targetLabelText = `Target: ${target}`;
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: [sourceLabelText, targetLabelText]
            });

  add_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add Markdown to PR Description
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const existingDescription = context.payload.pull_request.body;
            const newDescription = `- [ ] Task 1\n- [ ] Task 2\n- [ ] Task 3 `;
            const updatedDescription = existingDescription + '\n\n' + newDescription;
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              body: updatedDescription
            });
#   auto_comment:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: wow-actions/auto-comment@v1
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           issuesOpened: |
#             👋 @{{ author }}
#             Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
#             Please make sure you have given us as much context as possible.

#           pullRequestOpened: |
#             👋 @{{ author }}
#             Thank you for raising your pull request.
#             Please make sure you have followed our contributing guidelines. We will review it as soon as possible
